// Demo-only pixel-art item icons, hand-drawn as character grids (1 char = 1px)
// and compiled to crisp SVG data-URIs. Self-contained: no image files.

function icon(palette, rows) {
  const rects = [];
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      if (ch === '.') continue;
      let w = 1;
      while (x + w < row.length && row[x + w] === ch) w++;
      rects.push(`<rect x='${x}' y='${y}' width='${w}' height='1' fill='${palette[ch]}'/>`);
      x += w - 1;
    }
  });
  const size = Math.max(rows.length, rows[0].length);
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='${size}' height='${size}' viewBox='0 0 ${size} ${size}' shape-rendering='crispEdges'>${rects.join('')}</svg>`;
  return `url("data:image/svg+xml,${svg.replaceAll('#', '%23').replaceAll("'", '%27')}")`;
}

export const PIXEL_ICONS = {
  sword: icon(
    { W: '#e8e8f0', L: '#9d9db8', G: '#f5c542', H: '#8b5a2b', D: '#a8770f' },
    [
      '................',
      '.......W........',
      '......LWW.......',
      '......LWW.......',
      '......LWW.......',
      '......LWW.......',
      '......LWW.......',
      '......LWW.......',
      '......LWW.......',
      '....GGDWDGG.....',
      '.......H........',
      '.......H........',
      '.......H........',
      '......GDG.......',
      '................',
      '................',
    ],
  ),
  shield: icon(
    { K: '#9d9db8', B: '#2980b9', L: '#00d2ff', D: '#1a5276' },
    [
      '................',
      '..KKKKKKKKKKK...',
      '..KBBBBLBBBDK...',
      '..KBBBBLBBBDK...',
      '..KBLLLLLLLDK...',
      '..KBBBBLBBBDK...',
      '..KBBBBLBBBDK...',
      '..KBBBBLBBDDK...',
      '...KBBBLBBDK....',
      '....KBBLBDK.....',
      '.....KBLDK......',
      '......KDK.......',
      '.......K........',
      '................',
      '................',
      '................',
    ],
  ),
  bow: icon(
    { K: '#8b5a2b', D: '#5e3a1a', S: '#e0e0e0', G: '#f5c542' },
    [
      '................',
      '.....GKK........',
      '....KKK.S.......',
      '...KK...S.......',
      '..KK....S.......',
      '..KK....S.......',
      '..DK....S.......',
      '..DK....S.......',
      '..DK....S.......',
      '..KK....S.......',
      '..KK....S.......',
      '...KK...S.......',
      '....KKK.S.......',
      '.....GKK........',
      '................',
      '................',
    ],
  ),
  potionRed: icon(
    { K: '#31314a', R: '#e74c3c', D: '#c0392b', W: '#ffffff', G: '#8b5a2b' },
    [
      '................',
      '......GGG.......',
      '......GGG.......',
      '.....K...K......',
      '.....K...K......',
      '....K.....K.....',
      '...K..W....K....',
      '...K.......K....',
      '...KRRRRRRDK....',
      '...KRRRRRRDK....',
      '....KRRRRDK.....',
      '.....KKKKK......',
      '................',
      '................',
      '................',
      '................',
    ],
  ),
  potionBlue: icon(
    { K: '#31314a', R: '#2980b9', D: '#1a5276', W: '#ffffff', G: '#8b5a2b' },
    [
      '................',
      '......GGG.......',
      '......GGG.......',
      '.....K...K......',
      '.....K...K......',
      '....K.....K.....',
      '...K..W....K....',
      '...K.......K....',
      '...KRRRRRRDK....',
      '...KRRRRRRDK....',
      '....KRRRRDK.....',
      '.....KKKKK......',
      '................',
      '................',
      '................',
      '................',
    ],
  ),
  crown: icon(
    { G: '#f5c542', D: '#a8770f', R: '#e74c3c', B: '#00d2ff' },
    [
      '................',
      '................',
      '...G....G....G..',
      '...G....G....G..',
      '...GG...G...GG..',
      '...GGG.GGG.GGG..',
      '...GGGGGGGGGGG..',
      '...GGGGGGGGGGG..',
      '...GGRGGBGGRGG..',
      '...GDDDDDDDDDG..',
      '...GGGGGGGGGGG..',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ),
  gem: icon(
    { C: '#00d2ff', W: '#c9f4ff', D: '#00789b' },
    [
      '................',
      '................',
      '.....CCCCCC.....',
      '....CWCCCCDC....',
      '...CWCCCCCCDC...',
      '..CWCCCCCCCCDC..',
      '...DCCCCCCCCD...',
      '....DCCCCCCD....',
      '.....DCCCCD.....',
      '......DCCD......',
      '.......DD.......',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ),
  ring: icon(
    { G: '#f5c542', D: '#a8770f', R: '#e74c3c', W: '#ffb3ab' },
    [
      '................',
      '......WRR.......',
      '.....RRRRR......',
      '.....RRRRR......',
      '......RRR.......',
      '....GG...GG.....',
      '...GG.....GG....',
      '...G.......G....',
      '...G.......G....',
      '...G.......G....',
      '...DD.....DD....',
      '....DD...DD.....',
      '.....DDDDD......',
      '................',
      '................',
      '................',
    ],
  ),
  scroll: icon(
    { K: '#8b5a2b', W: '#e8d8a0', L: '#8b7a50', D: '#d4c088' },
    [
      '................',
      '................',
      '...KWWWWWWWWK...',
      '...KWWWWWWWWK...',
      '...KWLLLLLWWK...',
      '...KWWWWWWWWK...',
      '...KWLLLWWWWK...',
      '...KWWWWWWWWK...',
      '...KWLLLLWWWK...',
      '...KWWWWWWWWK...',
      '...KWWWWWWDWK...',
      '...KWWWWWWWWK...',
      '................',
      '................',
      '................',
      '................',
    ],
  ),
  meat: icon(
    { K: '#e8d8a0', M: '#c0392b', D: '#8e2a1d', W: '#e74c3c' },
    [
      '................',
      '................',
      '....MMMM........',
      '...MWWWMMM......',
      '...MWWWWMMM.....',
      '...MMWWWWMMM....',
      '....MMWWWWMM....',
      '.....MMMWWMM....',
      '......DMMMM.....',
      '.......DMM......',
      '........KK......',
      '.......KK.......',
      '......KK........',
      '................',
      '................',
      '................',
    ],
  ),
};
